### ISSUE TITLE
Prepare the library for an alpha release

### ISSUE THREAD

**Issue by jmeas** [jmeas/marionette.transition-region#3]
Let's move this project beyond prototype status and get it ready for an alpha release.

- Clean up the code
- Add unit tests
- Add unit tests against Marionette's tests to ensure BC

:dancers:

**Comment by jmeas** [comment]
Never gonna release this, actually

**Comment by peritus** [comment]
@jmeas What are you using then ? Lots has happened in Marionette in the last year, and with v3 on the horizon there might be better solutions to what this project might have provided. Do you have an overview ? Pointers ?

**Comment by jmeas** [comment]
Hey @peritus! You're right, a lot has happened with Marionette. And my opinions have changed since then, too.

First and foremost, a disclaimer: I'm not actively working on a project that extensively uses animations, so I'm not in any rush to figure out a solution. And when I do propose a solution, it won't be battle tested. So keep that in mind!

These two things have changed my opinion:

1. I don't believe that developers should ever interact with Regions directly. [This library](https://github.com/jmeas/marionette.base-view) (which is a WIP) is what I use in my own apps to allow for this to work. You can read [the WIP README here](https://github.com/jmeas/marionette.base-view/blob/first-version/README.md).

  So this is the first change. I don't plan to extend from / change / modify / think about regions in my apps anymore.

2. I'm working on a simpler API for animating, which you can read about here https://github.com/marionettejs/backbone.marionette/issues/2553#issuecomment-117812340
